# codemagic.yaml (VERSIÓN GRATUITA - DEBUG)
workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 30
    # ELIMINA la línea instance_type o usa "linux"
    environment:
      flutter: stable          # O tu versión exacta: flutter: 3.22.2
    scripts:
      - name: Instalar dependencias
        script: flutter pub get
      - name: Compilar APK debug
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk