# archivo: codemagic.yaml (colócalo en la raíz del repo)
workflows:
  android-release:
    name: Android Release APK
    max_build_duration: 30                         # minutos
    instance_type: linux                           # máquina Linux (más barata)
    environment:
      flutter: stable                              # versión Flutter que usará
      android_signing:                             # ← firma automática
        - keystore_reference: CM_KEYSTORE          # nombre que le pondrás en UI
    scripts:
      - name: Instalar dependencias
        script: flutter pub get
      - name: Compilar APK firmado
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk