workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: 3.24.3  # Versión específica estable y probada
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: | 
          flutter pub get
      - name: Flutter pub upgrade (fix dependencies)
        script: | 
          flutter pub upgrade
      - name: Build Flutter APK
        script: | 
          flutter build apk --debug
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - jemr1@example.com
        notify:
          success: true
          failure: true