workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2  # O linux | linux_x2 para ahorrar costos
    
    environment:
      flutter: stable
      
    scripts:
      - name: Install dependencies
        script: flutter packages pub get
        
      - name: Build Android APK
        script: flutter build apk --release
        
      - name: Build Android App Bundle (para Google Play)
        script: flutter build appbundle --release
    
    artifacts:
      # Para APK (instalación directa)
      - build/app/outputs/flutter-apk/app-release.apk
      
      # Para AAB (Google Play Store)
      - build/app/outputs/bundle/release/app-release.aab
      
      # O usa comodín para capturar ambos
      - build/app/outputs/**/*.apk
      - build/app/outputs/**/*.aab
    
    publishing:
      email:
        recipients:
          - montanoe664@gmail.com