# codemagic.yaml - Configuración para compilar APK DEBUG (sin keystore)
workflows:
  android-debug-workflow:
    name: Android Debug Build
    max_build_duration: 60
    environment:
      flutter: 3.24.5  # Versión estable específica
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Build DEBUG APK (sin keystore)
        script: | 
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - tu_email@ejemplo.com
        notify:
          success: true
          failure: true