# codemagic.yaml (versión SIN firma)
workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 30
    instance_type: linux
    environment:
      flutter: 3.22.2           # ← usa tu versión exacta (ejecuta `flutter --version` en tu PC)
    scripts:
      - name: Instalar dependencias
        script: flutter pub get
      - name: Compilar APK debug
        script: flutter build apk --debug          # ← debug no requiere keystore
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk